name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 自动同步
  workflow_dispatch:      # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史
          token: ${{ secrets.SYNC_TOKEN }}  # 使用 PAT 替代默认 GITHUB_TOKEN

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Sync with upstream
        run: |
          # 添加上游仓库
          git remote add upstream https://github.com/unifreq/openwrt_packit.git
          git fetch upstream

          # 合并更新（强制快进模式）
          git checkout master
          git merge --ff-only upstream/master

          # 使用 PAT 认证推送
          git push https://${{ secrets.SYNC_TOKEN }}@github.com/oppen321/openwrt_packit.git master
